### ISSUE TITLE
com.google.gwt.core.client.JavaScriptException: (TypeError) : $wnd.$(...).draggable is not a function

### ISSUE THREAD

**Issue by sebastian-de** [kiegroup/optaweb-employee-rostering#174]
Hey,

I tried to test the webapp on a local OpenShift installation. I'm at commit 411483b and I get this error message when viewing gwtui.html:
```
com.google.gwt.core.client.JavaScriptException: (TypeError) : $wnd.$(...).draggable is not a function
at Unknown.Hsd(Draggability.java:65)
at Unknown.Esd(Draggability.java:47)
at Unknown.nvd(ShiftGridObject.java:98)
at Unknown.bod(AbstractHasTimeslotGridObject.java:35)
at Unknown.Qrd(Lane.java:134)
at Unknown.Prd(Lane.java:109)
at Unknown.Rrd(Lane.java:215)
at Unknown.pxd(ShiftRosterPageViewportBuilder.java:109)
at Unknown.vxd(ShiftRosterPageViewportBuilder.java:105)
at Unknown.Jgd(Lockable.java:57)
at Unknown.sxd(ShiftRosterPageViewportBuilder.java:105)
at Unknown.Ls(SchedulerImpl.java:46)
at Unknown.Bs(SchedulerImpl.java:347)
at Unknown.Ps(SchedulerImpl.java:78)
at Unknown.Js(SchedulerImpl.java:141)
at Unknown.ms(Impl.java:309)
at Unknown.ps(Impl.java:361)
at Unknown.anonymous(Impl.java:78)
```

**Comment by Christopher-Chianelli** [comment]
Issue not applicable anymore since we moved from GWT to React.
