### ISSUE TITLE
Added the rule "All consecutive shifts must start on the same day",an error is reported

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#563]
rule "All consecutive shifts must start on the same day"
    when
        $s : Shift(
                employee != null,
                $e : employee,
                $firstStartDateTime : startDateTime,
                $firstEndDateTime : endDateTime)
        $s2: Shift(
                employee == $e,
                $firstEndDateTime == startDateTime,
                this != $s,
                $firstStartDateTime.toLocalDate() != startDateTime.toLocalDate())
    then
        scoreHolder.penalize(kcontext, $s.getLengthInMinutes() + $s2.getLengthInMinutes());
end

The backend error:
2021-02-05 15:36:58.920 ERROR 10116 --- [         task-1] o.o.e.s.solver.WannabeSolverManager      : Error solving for tenantId (1).

org.kie.api.runtime.rule.ConsequenceException: Exception executing consequence for rule "All consecutive shifts must start on the same day" in org.optaweb.employeerostering.service.solver: java.lang.IllegalStateException: The DRL rule (org.optaweb.employeerostering.service.solver:All consecutive shifts must start on the same day) does not match a @ConstraintWeight on the @ConstraintConfiguration annotated class.
	at org.drools.core.runtime.rule.impl.DefaultConsequenceExceptionHandler.handleException(DefaultConsequenceExceptionHandler.java:39) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.common.DefaultAgenda.handleException(DefaultAgenda.java:1301) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.phreak.RuleExecutor.innerFireActivation(RuleExecutor.java:438) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.phreak.RuleExecutor.fireActivation(RuleExecutor.java:380) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:136) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.phreak.RuleExecutor.evaluateNetworkAndFire(RuleExecutor.java:89) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.concurrent.AbstractRuleEvaluator.internalEvaluateAndFire(AbstractRuleEvaluator.java:33) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.concurrent.SequentialRuleEvaluator.evaluateAndFire(SequentialRuleEvaluator.java:43) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.common.DefaultAgenda.fireLoop(DefaultAgenda.java:1111) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.common.DefaultAgenda.internalFireAllRules(DefaultAgenda.java:1058) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.common.DefaultAgenda.fireAllRules(DefaultAgenda.java:1050) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.impl.StatefulKnowledgeSessionImpl.internalFireAllRules(StatefulKnowledgeSessionImpl.java:1345) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.impl.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1336) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.drools.core.impl.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1320) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.impl.score.director.drools.DroolsScoreDirector.calculateScore(DroolsScoreDirector.java:111) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.impl.score.director.AbstractScoreDirector.doAndProcessMove(AbstractScoreDirector.java:190) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.impl.constructionheuristic.decider.ConstructionHeuristicDecider.doMove(ConstructionHeuristicDecider.java:127) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.impl.constructionheuristic.decider.ConstructionHeuristicDecider.decideNextStep(ConstructionHeuristicDecider.java:101) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.impl.constructionheuristic.DefaultConstructionHeuristicPhase.solve(DefaultConstructionHeuristicPhase.java:75) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:99) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:189) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaweb.employeerostering.service.solver.WannabeSolverManager.lambda$3(WannabeSolverManager.java:146) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
Caused by: java.lang.IllegalStateException: The DRL rule (org.optaweb.employeerostering.service.solver:All consecutive shifts must start on the same day) does not match a @ConstraintWeight on the @ConstraintConfiguration annotated class.
	at org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder.impactScore(HardMediumSoftLongScoreHolder.java:176) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder.penalize(HardMediumSoftLongScoreHolder.java:113) ~[optaplanner-core-7.44.0.Final.jar:7.44.0.Final]
	at org.optaweb.employeerostering.service.solver.Rule_All_consecutive_shifts_must_start_on_the_same_day1058734825.defaultConsequence(Rule_All_consecutive_shifts_must_start_on_the_same_day1058734825.java:7) ~[na:na]
	at org.optaweb.employeerostering.service.solver.Rule_All_consecutive_shifts_must_start_on_the_same_day1058734825DefaultConsequenceInvokerGenerated.evaluate(Unknown Source) ~[na:na]
	at org.optaweb.employeerostering.service.solver.Rule_All_consecutive_shifts_must_start_on_the_same_day1058734825DefaultConsequenceInvoker.evaluate(Unknown Source) ~[na:na]
	at org.drools.core.phreak.RuleExecutor.innerFireActivation(RuleExecutor.java:431) ~[drools-core-7.44.0.Final.jar:7.44.0.Final]
	... 22 common frames omitted

**Comment by Christopher-Chianelli** [comment]
You need to add an `@ConstraintWeight` annotated field to https://github.com/kiegroup/optaweb-employee-rostering/blob/master/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/tenant/RosterConstraintConfiguration.java when you add a new constraint.

Add the following code to it:
```
    @ConstraintWeight("All consecutive shifts must start on the same day")
    private HardMediumSoftLongScore consecutiveShiftsMustStartOnSameDay = HardMediumSoftLongScore.ofHard(1);
```

along with corresponding setters and getters.
