### ISSUE TITLE
io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: java.lang.NoClassDefFoundE rror: org/hibernate/boot/jaxb/mapping/spi/ManagedType

### ISSUE THREAD

**Issue by aramcap** [kiegroup/optaweb-employee-rostering#640]
Hi, I've this problem when running maven:

```
$ mvn clean install -DskipTests -DskipITs

...
[INFO] OptaWeb Employee Rostering as a Service Parent ..... SUCCESS [  1.093 s]                                                                               
[INFO] OptaWeb Employee Rostering as a Service React Frontend SUCCESS [01:51 min]                                                                             
[INFO] OptaWeb Employee Rostering as a Service Quarkus Backend FAILURE [ 14.420 s]                                                                            
[INFO] OptaWeb Employee Rostering as a Service Benchmark .. SKIPPED                                                                                           
[INFO] OptaWeb Employee Rostering as a Service Documentation SKIPPED                                                                                          
[INFO] OptaWeb Employee Rostering as a Service Standalone . SKIPPED                                                                                           
[INFO] OptaWeb Employee Rostering as a Service Distribution SKIPPED                                                                                           
[INFO] ------------------------------------------------------------------------                                                                               
[INFO] BUILD FAILURE                                                                                                                                          
[INFO] ------------------------------------------------------------------------                                                                               
[INFO] Total time:  02:07 min                                                                                                                                 
[INFO] Finished at: 2021-06-17T17:28:25+02:00                                                                                                                 
[INFO] ------------------------------------------------------------------------                                                                               
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.0.CR3:build (default) on project optaweb-employee-rostering-backend: Failed to build quarku
s application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors                                                                   
[ERROR]         [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: java.lang.NoClassDefFoundE
rror: org/hibernate/boot/jaxb/mapping/spi/ManagedType                                                                                                         
[ERROR]         at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.defineJpaEntities(HibernateOrmProcessor.java:356)                                
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                             
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                           
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.hibernate.boot.jaxb.mapping.spi.ManagedType
[ERROR]         at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:447)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:397)
[ERROR]         ... 12 more
```

I don't found solution. Can anyone help me, please?

**Comment by triceo** [comment]
It's a problem on our end. We're already working on a fix:
https://github.com/kiegroup/optaplanner/pull/1385

**Comment by aramcap** [comment]
> It's a problem on our end. We're already working on a fix:
> [kiegroup/optaplanner#1385](https://github.com/kiegroup/optaplanner/pull/1385)

OK! Many thanks for ur help and sorry for my stupid query, I will follow this PR. Thanks @triceo!

**Comment by triceo** [comment]
No worries - thanks for your bug report!
